input.onButtonPressed(Button.A, function () {
    pins.analogWritePin(AnalogPin.P0, 100)
    pins.analogWritePin(AnalogPin.P1, 100)
    pins.analogWritePin(AnalogPin.P1, 10)
    pins.analogWritePin(AnalogPin.P0, 90)
    pins.analogWritePin(AnalogPin.P1, 110)
    pins.analogWritePin(AnalogPin.P1, 10)
    pins.analogWritePin(AnalogPin.P0, 80)
    pins.analogWritePin(AnalogPin.P1, 120)
    pins.analogWritePin(AnalogPin.P1, 10)
    pins.analogWritePin(AnalogPin.P0, 70)
    pins.analogWritePin(AnalogPin.P1, 130)
    pins.analogWritePin(AnalogPin.P1, 10)
    pins.analogWritePin(AnalogPin.P0, 60)
    pins.analogWritePin(AnalogPin.P1, 140)
    pins.analogWritePin(AnalogPin.P1, 10)
    pins.analogWritePin(AnalogPin.P0, 50)
    pins.analogWritePin(AnalogPin.P1, 150)
    pins.analogWritePin(AnalogPin.P1, 10)
    pins.analogWritePin(AnalogPin.P0, 40)
    pins.analogWritePin(AnalogPin.P1, 160)
    pins.analogWritePin(AnalogPin.P1, 10)
    pins.analogWritePin(AnalogPin.P0, 30)
    pins.analogWritePin(AnalogPin.P1, 170)
    pins.analogWritePin(AnalogPin.P1, 10)
    pins.analogWritePin(AnalogPin.P0, 20)
    pins.analogWritePin(AnalogPin.P1, 180)
    pins.analogWritePin(AnalogPin.P1, 10)
    pins.analogWritePin(AnalogPin.P0, 10)
    pins.analogWritePin(AnalogPin.P1, 190)
    pins.analogWritePin(AnalogPin.P1, 10)
    pins.analogWritePin(AnalogPin.P0, 0)
    pins.analogWritePin(AnalogPin.P1, 200)
    pins.analogWritePin(AnalogPin.P1, 10)
})
basic.forever(function () {
	
})
